### ISSUE TITLE
PodSecurityPolicy in DeploymentConfig ?

### ISSUE THREAD

**Issue by manosnoam** [supriya-premkumar/DockerAutoDeploy#1]
Hi @supriya-premkumar 
This is a question regarding your post:
https://github.com/kubernetes-retired/external-storage/issues/1145#issuecomment-512598941

```
apiVersion: policy/v1beta1 
kind: PodSecurityPolicy 
  metadata: 
    name: example 
  spec: 
    volumes: 
     - nfs 
```

I could not reply in the above post, thus decided to ask here, hope it's ok.
Can you please explain how to add above config in a DeploymentConfig yaml ?

For example, this is my DeploymentConfig, where should I add your PodSecurityPolicy config in it:

```
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  ...
spec:
  ...
  template:
    metadata:
      ...
    spec:
      containers:
        - env:
          ...
          volumeMounts:
            - mountPath: /mnt/my-nfs
              name: my-nfs
      ...
      volumes:
        - name: my-nfs
          nfs:
            server: my.server.com
            path: "/mnt/my-nfs"
...
```

Thanks!
